name: Build Updatesite

on: workflow_dispatch

jobs:
  DataFlowAnalysis-Product:
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@v3.4
    with:
      use-display-output: true
      deploy-updatesite: 'products/org.dataflowanalysis.product/target/deploy'
    secrets:
      SERVER_SSH_KEY: ${{ secrets.PALLADIO_UPDATESITE_SSH }}
      REMOTE_HOST: ${{ secrets.PALLADIO_REMOTE_HOST }}
      REMOTE_PORT: ${{ secrets.PALLADIO_REMOTE_PORT }}
      REMOTE_USER: ${{ secrets.PALLADIO_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.PALLADIO_REMOTE_TARGET }}
