name: Upload artifacts on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: 'self-hosted'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
      
    - name: Verify with Maven
      shell: bash
      run: mvn clean verify

    - name: Add artifacts to release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        repository: DataFlowAnalysis/product
        files: |
          products/org.dataflowanalysis.product/target/deploy/DataFlowAnalysis.linux.gtk.x86_64.zip
          products/org.dataflowanalysis.product/target/deploy/DataFlowAnalysis.macosx.cocoa.x86_64.zip
          products/org.dataflowanalysis.product/target/deploy/DataFlowAnalysis.win32.win32.x86_64.zip
          products/org.dataflowanalysis.product/target/deploy/DataFlowAnalysis.macosx.cocoa.aarch64.zip
